INSERT INTO USER (USER_NAME, PASSWORD) VALUES ('arsal', '123');
INSERT INTO USER (USER_NAME, PASSWORD) VALUES ('jamal', '234');
INSERT INTO AUTH_GROUP (USER_NAME, AUTH_GROUP) VALUES ('arsal','USER');
INSERT INTO AUTH_GROUP (USER_NAME, AUTH_GROUP) VALUES ('arsal','ADMIN');
INSERT INTO AUTH_GROUP (USER_NAME, AUTH_GROUP) VALUES ('jamal','USER');