CREATE TABLE USER (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
    USER_NAME VARCHAR(128) NOT NULL UNIQUE ,
    PASSWORD VARCHAR(256) NOT NULL
);

CREATE TABLE AUTH_GROUP (
    AUTH_USER_GROUP_ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
    USER_NAME VARCHAR(128) NOT NULL,
    AUTH_GROUP VARCHAR(256) NOT NULL,
    CONSTRAINT USER_AUTH_USER_GRP_FK FOREIGN KEY(USER_NAME) REFERENCES USER(USER_NAME),
    UNIQUE(USER_NAME,AUTH_GROUP)
);