INSERT INTO RESTAURANT (REST_NAME, REST_ADDRESS, REST_LOCATION) VALUES ('KababJee', 'Highway', 'Sorab Goth');
INSERT INTO RESTAURANT (REST_NAME, REST_ADDRESS, REST_LOCATION) VALUES ('AghaJuice', 'Gulshan', 'Disco More');
INSERT INTO RESTAURANT (REST_NAME, REST_ADDRESS, REST_LOCATION) VALUES ('OPTP', 'Jauhar', 'Block 16');
INSERT INTO RESTAURANT (REST_NAME, REST_ADDRESS, REST_LOCATION) VALUES ('BroadWay', 'Gulshan', 'Disco More');
INSERT INTO RESTAURANT (REST_NAME, REST_ADDRESS, REST_LOCATION) VALUES ('HotnRoll', 'Tariq Road', '3 Minar Chaurangi');